[workspace]
resolver = "2"
members = ["crates/avatar-formats", "crates/avatar-export", "crates/avatarextract", "crates/avatar-aura", "crates/stfs", "crates/bcdec", "crates/avatar-bake", "crates/avatar-view", "crates/build-assets"]

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false

[workspace.dependencies]
anyhow = "1"
thiserror = "2"
glam = "0.34"
bytemuck = { version = "1", features = ["derive"] }
image = { version = "0.25", default-features = false, features = ["png"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wgpu = "30"
pollster = "1"
eframe = { version = "0.36", default-features = false, features = ["default_fonts", "wgpu", "accesskit"] }
rfd = "0.17"
directories = "6"
toml = "1.1"
include_dir = "0.7"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
sha1 = "0.11"
crc32fast = "1.5"
miniz_oxide = "0.9"

[profile.release]
lto = "thin"
codegen-units = 1
